# Install dependencies
FROM debian:latest AS builder
RUN apt-get update 
RUN apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3 psmisc
RUN apt-get clean

# Clone the flutter repo
# Temporary fix while the cuppertino_icons package is not fixed to work with Flutter 3.13.0 (latest stable release).
RUN git clone --branch 3.10.6 https://github.com/flutter/flutter.git /usr/local/flutter

# Set flutter path
ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"

# Enable flutter web
# RUN flutter channel stable
# RUN flutter upgrade
RUN flutter config --enable-web

# Run flutter doctor
RUN flutter doctor -v

# Copy the app files to the container
COPY . /app

# Set the working directory to the app files within the container
WORKDIR /app

# Create env file
RUN touch .env && echo DECK2_URL="https://deck2.sinfo.org/api" > .env

# Get App Dependencies and Build it
RUN flutter clean
RUN flutter pub get
RUN flutter build web --release

# Run the app on NGINX
FROM nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build/web/ /web/
