version: '3.3'
services:
    api:
        build: 
            context: '.'
            dockerfile: './Dockerfile_test'
        links:
            - mongodb:db
        depends_on:
            - mongodb
        container_name: 'deck2_testing'
        environment:
            - 'DECK2_DB_URL=mongodb://db:27017'
            - 'DECK2_GOOGLE_OAUTH_CLIENT_SECRET=gytpJdHCu1on-EiKBeQjY7oT'
            - 'DECK2_GOOGLE_OAUTH_CLIENT_ID=936462102746-fumunq371c3ecogk977gi7e63oq825mi.apps.googleusercontent.com'
            - 'DECK2_JWT_SECRET=hello_there'
    mongodb:
        image: mongo:4.0.4
        container_name: "deck2_testing_mongodb"
        command: mongod --smallfiles --logpath=/dev/null