version: '3.3'
services:
    sut:
        build: 
            context: '.'
            dockerfile: './Dockerfile_test'
        links:
            - mongodb:db
        depends_on:
            - mongodb
        environment:
            - 'DECK2_DB_URL=mongodb://db:27017'
            - 'DECK2_GOOGLE_OAUTH_CLIENT_SECRET=THIS_IS_A_SECRET'
            - 'DECK2_GOOGLE_OAUTH_CLIENT_ID=THIS_IS_A_SECRET'
            - 'DECK2_JWT_SECRET=THIS_IS_A_SECRET'
    mongodb:
        image: mongo:4.0.4
        container_name: "deck2_testing_mongodb"
        command: mongod --smallfiles --logpath=/dev/null