version: '3.3'
services:
    api:
        build: 
            context: '.'
            dockerfile: './Dockerfile'
        ports:
            - '8080:8080'
        container_name: 'deck2'
        environment:
            - 'DECK2_DB_URL=mongodb://host.docker.internal:27017'
            - 'DECK2_HOST=0.0.0.0'
            - 'DECK2_GOOGLE_OAUTH_CLIENT_SECRET=THIS_IS_A_SECRET'
            - 'DECK2_GOOGLE_OAUTH_CLIENT_ID=THIS_IS_A_SECRET'
            - 'DECK2_JWT_SECRET=THIS_IS_A_SECRET'