############################
# STEP 1 generate and validate swagger specification
############################
FROM quay.io/goswagger/swagger AS swagger-validator

WORKDIR $GOPATH/src/github.com/sinfo/deck2
COPY . .

RUN swagger flatten ./swagger/swagger.json --compact -o /go/bin/swagger.json
RUN swagger validate /go/bin/swagger.json -q


############################
# STEP 2 run tests
############################
FROM golang:1.23-alpine AS builder

WORKDIR $GOPATH/src/github.com/sinfo/deck2
COPY . .

RUN apk --no-cache add ca-certificates
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go test -c ./src/router

CMD ["./router.test"]